### ISSUE TITLE
Is this really necessary?

### ISSUE THREAD

**Issue by ateesdalejr** [vutondesign/site-status#1]
Are we aiming for a sarcastic vibe here? 📦

**Comment by vutondesign** [comment]
I wouldn't say it's very necessary, however, it has come in handy. I like to take my site down when I'm doing full re-designs etc. and I make index.html re-direct to here. (There would be a reason for the status, eg. "Undergoing major maintenance")

**Comment by ateesdalejr** [comment]
OK, just wondering. :) When you are developing your site or making major changes you can always use a separate branch and call it `develop` and then pull your changes into the default branch when your finished. That way your users never see any changes.

**Comment by vutondesign** [comment]
Yeah, I know. I use this more when I'm making domain changes etc.
